### ISSUE TITLE
default confiig missining db_path and backend option

### ISSUE THREAD

**Issue by gozes** [MichelBoucey/cayley-client#1]
cayley supports a good number of backbends but I don't see a way with this library to make a cayley config where I can pass a backend and a path to the db if I am starting from a new DB rather then using one that already exist

**Comment by MichelBoucey** [comment]
This library is a client for the Cayley server, not for its backends, what ever they are.

**Comment by gozes** [comment]
True, but when you run cayley you need to give it a path to the db and a
local regardless of the backend. Your library assume That there's a cayley
instance already running and with date to query but offers now way to init
a cayley db.

**Comment by MichelBoucey** [comment]
Sorry but  for now the feature you ask for doesn't belong to [Cayley HTTP API](https://github.com/google/cayley/blob/master/docs/HTTP.md) that this library implements.  So you can perhaps ask the Cayley project for this kind of admin commands, like init/delete databases, through the RESTful API, and then I will implement it.
