### ISSUE TITLE
Compile failure with GHC 7.8 / Inaccurate version bounds

### ISSUE THREAD

**Issue by hvr** [MichelBoucey/cayley-client#3]
The build-dependencies have inaccurate versions bounds. Please be aware that accurate version bounds are mandated by the [PVP](http://pvp.haskell.org/), and packages are expected to follow the PVP as part of the Hackage guidelines.  This has various knock off consequences, such as Hackage possibly not being able to generate Haddock documentation for your package, install-plans degrading over time, as well generally resulting in a poor experience for users since they'll risk running into the  compilation errors caused by inaccurate version bounds.

The `cabal gen-bounds` command can be used to help infer an initial set of version bounds, see  [Cabal User Guide | Generating dependency version bounds](http://cabal.readthedocs.io/en/latest/developing-packages.html#generating-dependency-version-bounds) for more details.

Specifically, the cabal file claims compatibility with `base >= 4.7`, however GHC 7.8 disagrees (see below). You can either restore compatibility with GHC 7.8 or just declare `base >= 4.8`.

In the latter case, you don't need to upload a new release; you can just fixup the meta-data on Hackage yourself via e.g.

  https://hackage.haskell.org/package/cayley-client-0.2.1.0/cayley-client.cabal/edit

If you have any questions, please let me know!

```
Configuring component lib from cayley-client-0.2.1.0
Preprocessing library cayley-client-0.2.1.0...
[1 of 3] Compiling Database.Cayley.Types ( Database/Cayley/Types.hs, /tmp/matrix-worker/1480322764/dist-newstyle/build/x86_64-linux/ghc-7.8.4/cayley-client-0.2.1.0/build/Database/Cayley/Types.o )

Database/Cayley/Types.hs:82:10: Not in scope: ‘<$>’

Database/Cayley/Types.hs:83:22: Not in scope: ‘<*>’

Database/Cayley/Types.hs:84:24: Not in scope: ‘<*>’

Database/Cayley/Types.hs:85:21: Not in scope: ‘<*>’

Database/Cayley/Types.hs:104:31: Not in scope: ‘<$>’

Database/Cayley/Types.hs:105:35: Not in scope: ‘<*>’

Database/Cayley/Types.hs:106:39: Not in scope: ‘<*>’

Database/Cayley/Types.hs:107:41: Not in scope: ‘<*>’

Database/Cayley/Types.hs:108:46: Not in scope: ‘<*>’

Database/Cayley/Types.hs:113:31: Not in scope: ‘<$>’

Database/Cayley/Types.hs:114:40: Not in scope: ‘<*>’

Database/Cayley/Types.hs:115:40: Not in scope: ‘<*>’
```

**Comment by MichelBoucey** [comment]
Thank you 1°/ to report this build issue... it's seems to me that is about AMP transition. I knew it will arrived. I'm gonna keep GHC 7.8 compatibility and gonna work to do so, 2°/ for gen-bounds, that I didn't know its existence.

**Comment by MichelBoucey** [comment]
I was finally forced to set base >= 4.8 (on hackage too) because of the lack of an instance in `binary` in the older version needed for compatibility with my package.

**Comment by hvr** [comment]
Makes sense... is the lower version bound on `binary` still accurate now (or is this not a property of the `binary` version?)?

**Comment by MichelBoucey** [comment]
The lower version bound on `binary` was already okay and still is.

FYI: I use stack to decide wich versions set my packages must use.

**Comment by hvr** [comment]
Just be aware that Stack is not very good at finding counter-examples disproving version-ranges... that's one of the reasons I'm working on http://matrix.hackage.haskell.org/ to help test version ranges more thoroughly, as they are essential for cabal's constraint solver to come up with reasonable install-plans.

**Comment by MichelBoucey** [comment]
I only knew Stack to get out of cabal hell, which truly painful. I really never heard of matrix-builder despite the fact that I follow Haskell news since a long time now... is it enough mature? Question: is cabal gen-bounds help solve in itself the cabal hell issue?

**Comment by hvr** [comment]
The matrix builder is work in progress; I'm just in the process of rewriting the matrix builder in terms of [cabal's new nix-style features](http://cabal.readthedocs.io/en/latest/nix-local-build-overview.html). But I hope to be able to make an announcement soon...

Unfortunately, there is no single easy solution to "cabal hell", there's just various ways to attack the problem with different trade-offs. If you follow haskell news, you may have heard about https://www.well-typed.com/blog/2015/01/how-we-might-abolish-cabal-hell-part-2/ which tries to elaborate on that, and describes our multi-pronged plan to attack the problem.

**Comment by MichelBoucey** [comment]
So you follow and implement a nix-style (quasi-)solution... okay, so what's currently the better solution? For me it was Stack (because I didn't know any other (better) alternative)... the cabal's nix-style new features?

**Comment by hvr** [comment]
Yes, ultimately I believe that cabal's approach is more powerful/general than the partial solution that Stack is currently pursuing. At this point we have a bit of an unsatisfying situation though, Stack is currently the more polished tool with a friendly UI, whereas cabal's strength is its implementation/integration of hackage-security/mirroring facilities, support for Backpack, solver/index-related features (we recently added support for freezing the hackage index per-project, which also allows things like `git bisect` to reconstruct install-plans),  and the more powerful nix-style cache store architecture (ever tried to switch between a profiled/non-profiled build with Stack?); but the big down-side is that the UI-side to that machinery is not yet polished enough. However, with the new machinery, Stack's stackage features are just a special case of the more powerful facilities offered by cabal, e.g. stackage resolvers are merely a set of constraints you enable for your project, i.e. it's basically just a kind of freeze to cabal. There's a lot of time & effort we're investing into cabal and its surrounding infrastructure that I can't go into details here... so stay tuned... :-)

That being said, keep using Stack for the meantime, and give cabal a try when we declare `cabal new-build` to be ready for everyone (i.e. not only early adopters).

**Comment by MichelBoucey** [comment]
Okay. I had already understood how Stack gets things done by freezing sets of versions. Thanks for those details... sure I'll give a try to the new coming cabal. BTW it's a bit sad that community split (mainly for sure) because of Cabal Hell.
